/*
------------------------------------------------
Generated by Cradle 2.0.2.0
https://github.com/daterre/Cradle

Original file: CWMA.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @CWMA: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@CWMA()
	{
		this.StartPassage = "Cold Open";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Cold Open

	void passage1_Init()
	{
		this.Passages[@"Cold Open"] = new StoryPassage(@"Cold Open", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"Jordy");
		yield return lineBreak();
		yield return text(@"And that’s how I discovered where the cold sore came from.  I have no idea how that came up?  Sorry, I talk a lot when I’m driving.");
		yield return lineBreak();
		yield return link(@"1-1", @"1-1", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: 1-1

	void passage2_Init()
	{
		this.Passages[@"1-1"] = new StoryPassage(@"1-1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"Gina");
		yield return lineBreak();
		yield return text(@"...");
		yield return lineBreak();
		yield return link(@"1-2", @"1-2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: 1-2

	void passage3_Init()
	{
		this.Passages[@"1-2"] = new StoryPassage(@"1-2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text(@"Player");
		yield return lineBreak();
		yield return text(@"...");
		yield return lineBreak();
		yield return link(@"1-3", @"1-3", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: 1-3

	void passage4_Init()
	{
		this.Passages[@"1-3"] = new StoryPassage(@"1-3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text(@"Jordy");
		yield return lineBreak();
		yield return text(@"...");
		yield return lineBreak();
		yield return link(@"1-4", @"1-4", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: 1-4

	void passage5_Init()
	{
		this.Passages[@"1-4"] = new StoryPassage(@"1-4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text(@"Gina");
		yield return lineBreak();
		yield return text(@"Soo... 5 more minutes till the theater?");
		yield return lineBreak();
		yield return link(@"1-5", @"1-5", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: 1-5

	void passage6_Init()
	{
		this.Passages[@"1-5"] = new StoryPassage(@"1-5", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text(@"Jordy");
		yield return lineBreak();
		yield return text(@"Nope, 7 minutes. I missed two turns earlier.  Sorry.");
		yield return lineBreak();
		yield return link(@"Internal 1-1", @"Internal 1-1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7: Internal 1-1

	void passage7_Init()
	{
		this.Passages[@"Internal 1-1"] = new StoryPassage(@"Internal 1-1", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text(@"Thoughts");
		yield return lineBreak();
		yield return text(@"Well this is awkward, hopefully not too awkward… Okay, probably too awkward.");
		yield return lineBreak();
		yield return link(@"Internal 1-2", @"Internal 1-2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: Internal 1-2

	void passage8_Init()
	{
		this.Passages[@"Internal 1-2"] = new StoryPassage(@"Internal 1-2", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(@"Anxiety");
		yield return lineBreak();
		yield return text(@"Just play it cool, maybe they won’t notice how much of a mess you are.  Think about it, you haven’t had the chance to embarrass yourself (delay) yet.");
		yield return lineBreak();
		yield return link(@"Internal 1-3", @"Internal 1-3", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: Internal 1-3

	void passage9_Init()
	{
		this.Passages[@"Internal 1-3"] = new StoryPassage(@"Internal 1-3", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text(@"Thoughts");
		yield return lineBreak();
		yield return text(@"Is that supposed to make me feel better?");
		yield return lineBreak();
		yield return link(@"Internal 1-4", @"Internal 1-4", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #10: Internal 1-4

	void passage10_Init()
	{
		this.Passages[@"Internal 1-4"] = new StoryPassage(@"Internal 1-4", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text(@"Anxiety");
		yield return lineBreak();
		yield return text(@"Look on the bright side, you’ve made a wonderful new friend.  This Dryve driver, Jordy, who is good at oversharing and not so good at driving..  Which is exactly why you came out on this date, to talk to the rideshare guy. ");
		yield return lineBreak();
		yield return link(@"Internal 1-5", @"Internal 1-5", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: Internal 1-5

	void passage11_Init()
	{
		this.Passages[@"Internal 1-5"] = new StoryPassage(@"Internal 1-5", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text(@"Player");
		yield return lineBreak();
		yield return text(@"No, this is salvageable, what do I do?");
		yield return lineBreak();
		yield return link(@"Question 1-1", @"Question 1-1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #12: Choice 1-1

	void passage12_Init()
	{
		this.Passages[@"Choice 1-1"] = new StoryPassage(@"Choice 1-1", new string[]{ "Player", }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text(@"Player");
		yield return lineBreak();
		yield return text(@"No problem, the first few minutes are previews anyway.  Let it Ride.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #13: Choice 1-2

	void passage13_Init()
	{
		this.Passages[@"Choice 1-2"] = new StoryPassage(@"Choice 1-2", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text(@"Player");
		yield return lineBreak();
		yield return text(@"Hey, I’ve got a joke!");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #14: Choice 1-3

	void passage14_Init()
	{
		this.Passages[@"Choice 1-3"] = new StoryPassage(@"Choice 1-3", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text(@"Player");
		yield return lineBreak();
		yield return text(@"How was your day?");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #15: Choice 1-4

	void passage15_Init()
	{
		this.Passages[@"Choice 1-4"] = new StoryPassage(@"Choice 1-4", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text(@"Player");
		yield return lineBreak();
		yield return text(@"*Tries to unlock door*");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #16: Question 1-1

	void passage16_Init()
	{
		this.Passages[@"Question 1-1"] = new StoryPassage(@"Question 1-1", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text(@"Player");
		yield return lineBreak();
		yield return link(@"Play it cool", @"Choice 1-1", null);
		yield return lineBreak();
		yield return link(@"Make a joke", @"Choice 1-2", null);
		yield return lineBreak();
		yield return link(@"Ask her about her day", @"Choice 1-3", null);
		yield return lineBreak();
		yield return link(@"Escape", @"Choice 1-4", null);
		yield return lineBreak();
		yield break;
	}


}